# Generated by Django 4.0.4 on 2023-01-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=10000)),
                ('categories', models.CharField(max_length=500)),
                ('pictures1', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('pictures2', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('pictures3', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('pictures4', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('pictures5', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('pictures6', models.ImageField(blank=True, null=True, upload_to='product_photos')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=5000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
