# Generated by Django 4.0.4 on 2023-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_ratings_product_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
