# Generated by Django 4.0.4 on 2023-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='my_order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(),
        ),
    ]
