# Generated by Django 4.0.4 on 2023-01-24 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_my_order_purchased_my_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('apt_suit', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=10)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
