# Generated by Django 4.0.4 on 2023-01-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_billing_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_adress',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing_adress',
            name='stripe',
            field=models.BooleanField(default=False),
        ),
    ]
