# Generated by Django 4.0.4 on 2023-01-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_billing_adress_paypal_billing_adress_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_adress',
            name='paypal',
        ),
        migrations.RemoveField(
            model_name='billing_adress',
            name='stripe',
        ),
        migrations.AddField(
            model_name='billing_adress',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('paypal', 'paypal')], max_length=10),
        ),
    ]
