# Generated by Django 4.0.4 on 2023-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_billing_adress_paypal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_adress',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal')], max_length=6),
        ),
    ]
