# Generated by Django 4.0.4 on 2023-01-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_billing_adress_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_adress',
            old_name='payment_type',
            new_name='payment_types',
        ),
    ]
