# Generated by Django 4.0.4 on 2023-01-25 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_order_billing_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='disput_state',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('resolved', 'resolved')], default='no', max_length=15),
        ),
        migrations.AddField(
            model_name='my_order',
            name='order_state',
            field=models.CharField(choices=[('not_ordered', 'not_ordered'), ('processesing', 'processesing'), ('shipped', 'shipped'), ('received', 'received')], default='not_ordered', max_length=15),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.my_order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
