# Generated by Django 4.0.4 on 2023-02-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_ratings_product_ratings_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='products.my_order'),
        ),
    ]
