# Generated by Django 4.0.4 on 2023-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_ratings_order_ratings_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_adress',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billing_adress',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='billing_adress',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='billing_adress',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
